server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: example
    url: jdbc:postgresql://localhost:5432/example
    username: example
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

application.jwt.secretKey: exampleexampleexampleexampleexampleexampleexampleexampleexampleexample
application.jwt.tokenPrefix: Bearer
application.jwt.tokenExpiration: 3600000
