server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
#    password: example
#    url: jdbc:postgresql://localhost:5432/example
#    username: example
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: false

  #mail:
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

application.jwt.secretKey: exampleexampleexampleexampleexampleexampleexampleexampleexampleexample
application.jwt.tokenPrefix: Bearer
application.jwt.tokenExpiration: 900000
