version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6
  gradle: circleci/gradle@2.2.0

workflows:
  java-ci-cd:
    jobs:
      - gradle/test
      - heroku/deploy-via-git:
          requires:
            - gradle/test
          filters:
            branches:
              only: master