SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE topic_article RESTART IDENTITY;
TRUNCATE TABLE article_word RESTART IDENTITY;
TRUNCATE TABLE confirmation_token RESTART IDENTITY;

TRUNCATE TABLE account RESTART IDENTITY;
TRUNCATE TABLE article RESTART IDENTITY;
TRUNCATE TABLE topic RESTART IDENTITY;
TRUNCATE TABLE word RESTART IDENTITY;

ALTER SEQUENCE account_sequence RESTART WITH 1;
-- ALTER SEQUENCE article_id_seq RESTART WITH 1;
-- ALTER SEQUENCE article_word_id_seq RESTART WITH 1;
ALTER SEQUENCE confirmation_token_sequence RESTART WITH 1;
-- ALTER SEQUENCE topic_id_seq RESTART WITH 1;
-- ALTER SEQUENCE word_id_seq RESTART WITH 1;

SET FOREIGN_KEY_CHECKS = 1;